export const UPDATE_LOGIN_EMAIL = "UPDATE_LOGIN_EMAIL";
export const UPDATE_LOGIN_PASSWORD = "UPDATE_LOGIN_PASSWORD";
export const UPDATE_CREATE_EMAIL = "UPDATE_CREATE_EMAIL";
export const UPDATE_CREATE_PASSWORD = "UPDATE_CREATE_PASSWORD";
export const UPDATE_CONFIRM_PASSWORD = "UPDATE_CONFIRM_PASSWORD";
export const TOGGLE_CREATE_USER = "TOGGLE_CREATE_USER";

export const LOGIN_USER = "LOGIN_USER";
export const CREATE_USER = "CREATE_USER";
